Workflow:
  '@WorkflowId': '{36c99645-93b3-ee11-a569-000d3a5c657e}'
  '@Name': SAP Table Copilot
  '@Description': Call this flow from Power Virtual Agents.
  JsonFileName: /modernflows/36c99645-93b3-ee11-a569-000d3a5c657e/SAPTableCopilot-36C99645-93B3-EE11-A569-000D3A5C657E.json
  Type: 1
  Subprocess: 0
  Category: 5
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.0
  IsCustomizable: 1
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  PrimaryEntity: none
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': SAP Table Copilot
  Descriptions:
    Description:
      '@languagecode': 1033
      '@description': Call this flow from Power Virtual Agents.
