environmentvariabledefinition:
  '@schemaname': cr680_AzureOpenAITableCopilotKEY
  defaultvalue: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  description:
    '@default': AzureOpenAITableCopilotKEY
    label:
      '@description': AzureOpenAITableCopilotKEY
      '@languagecode': 1033
  displayname:
    '@default': AzureOpenAITableCopilotKEY
    label:
      '@description': AzureOpenAITableCopilotKEY
      '@languagecode': 1033
  introducedversion: 1.0.0.0
  iscustomizable: 1
  isrequired: 0
  secretstore: 0
  type: 100000000
