environmentvariabledefinition:
  '@schemaname': cr680_AzureOpenAITableCopilotURL
  defaultvalue: https://your-endpoint.openai.azure.com/openai/deployments/gpt-4-32k/chat/completions?api-version=2023-07-01-preview
  description:
    '@default': AzureOpenAITableCopilotURL
    label:
      '@description': AzureOpenAITableCopilotURL
      '@languagecode': 1033
  displayname:
    '@default': AzureOpenAITableCopilotURL
    label:
      '@description': AzureOpenAITableCopilotURL
      '@languagecode': 1033
  introducedversion: 1.0.0.0
  iscustomizable: 1
  isrequired: 0
  secretstore: 0
  type: 100000000
